.PHONY: clean, all
CC = gcc
# /opt/trendchip/buildroot-gcc493_glibc222_arm32_32bServer/usr/bin/arm-buildroot-linux-gnueabi-gcc

all:
	gcc -std=c99 -pthread -o pipe_mutex main.c
clean:
	rm -rf pipe_mutex
